### ISSUE TITLE
word normalize support for mecab tokenizer

### ISSUE THREAD

**Issue by sobamchan** [himkt/konoha#108]
Hi, I have been using konoha a lot lately, thanks for the great lib.

I have a question about MeCab pipeline.
I see konoha's `normalized_form` only supports Sudachi.
Is there any particular reason why it does not support MeCab? 

If there is not, I would like to contribute here.

Thanks.

**Comment by himkt** [comment]
Thank you for your interest!
The output of `normalized_form` is the unique feature of Sudachi.
As far as I understand, MeCab doesn't provide this information.
For more detail, please refer to the documentation. :pray:

https://github.com/WorksApplications/Sudachi#mecab--kuromoji-%E3%81%A8%E3%81%AE%E6%AF%94%E8%BC%83
<img width="1421" alt="Screen Shot 2020-08-06 at 15 37 28" src="https://user-images.githubusercontent.com/5164000/89499333-caa79e80-d7fa-11ea-83b8-ae1b67afed59.png">

**Comment by sobamchan** [comment]
Ah, ok my bad.
I thought `normalized_form` is equivalent to lemmatize/stemming (which I wanted for my project).

Thanks for your time!

**Comment by himkt** [comment]
<img width="725" alt="Screen Shot 2020-08-06 at 16 45 38" src="https://user-images.githubusercontent.com/5164000/89505238-4823dc80-d804-11ea-96f0-b94f953a2c66.png">


I'm wondering if `base_form` would be the thing you want.
(I think `normalized_form` is the normalization of `base_form` in Sudachi)

**Comment by himkt** [comment]
@sobamchan 

<img width="725" alt="Screen Shot 2020-08-06 at 16 45 38" src="https://user-images.githubusercontent.com/5164000/89505238-4823dc80-d804-11ea-96f0-b94f953a2c66.png">


I'm wondering if `base_form` would be the thing you want.
(I think `normalized_form` is the normalization of `base_form` in Sudachi)

**Comment by sobamchan** [comment]
Cool, I didn't know the token instance has base_form property.
This is exactly what I wanted, I already wrote a parser myself but will update with this.
Thanks!
