### ISSUE TITLE
It is better to be pre-compiled a regular expression objects of the SentenceTokenizer class

### ISSUE THREAD

**Issue by hppRC** [himkt/konoha#114]
Hi, @himkt 
Now [SentenceTokenizer](https://github.com/himkt/konoha/blob/master/konoha/sentence_tokenizer.py) is like below.

```python
class SentenceTokenzier
    PATTERNS = [
        r"（.*?）",
        r"「.*?」",
    ]

    def tokenize(self, document):
        for pattern in SentenceTokenizer.PATTERNS:
            pattern = re.compile(pattern)
            document = re.sub(pattern, self.conv_period, document)
        ....
```

However, this would harm speed since the regular expression objects is compiled in every loop.
I would say that the regular expression objects should be **pre-compiled**, like below.

```python
class SentenceTokenizer:
    PATTERNS = [
        re.compile(r"（.*?）"),
        re.compile(r"「.*?」"),
    ]
```

Then, we use them with fewer overheads.

```python
class SentenceTokenzier
    ...
    def tokenize(self, document):
        for pattern in SentenceTokenizer.PATTERNS:
            document = pattern.sub(self.conv_period, document)
```

I created an evaluation repository. 
[hppRC/konoha-sentence-tokenizer-regex-compile](https://github.com/hppRC/konoha-sentence-tokenizer-regex-compile)
Please check it out for more detailed results.

**Comment by himkt** [comment]
Hi @hppRC, thank you for raising the issue and sharing well-written benchmarks!
I'm working on modifying a sentence tokenizer based on your suggestion in #117.

**Comment by hppRC** [comment]
Wow, that PR is great!!
Thank you for your prompt response.
