### ISSUE TITLE
konoha not in acceptable choices for dataset_reader.tokenizer.type

### ISSUE THREAD

**Issue by Akirtn** [himkt/konoha#115]
I have reproduced it on Google colab.

https://colab.research.google.com/drive/1fPu5iYhE-t8ufbgM24trDJ-o4ZL7FdX9?usp=sharing

I have taken Jsoonet from https://qiita.com/klis/items/f1d29cb431d1bf879898.

I would be grateful for any advice.

**Comment by himkt** [comment]
Hello @Akirtn, thank you for reporting the issue!
I reproduced your error and it is caused because konoha doesn't follow the interface change in AllenNLP.

I'm working on fixing the issue in #116.
