### ISSUE TITLE
bump natto-py version to >=1.0.0 to avoid use2to3 error from setuptools.

### ISSUE THREAD

**Issue by HCharlie** [himkt/konoha#163]
https://github.com/buruzaemon/natto-py/issues/119
since Konoha depends on natto-py, it will cause the same issue.

**Comment by himkt** [comment]
Thank you so much for reporting @HCharlie. I just released konoha v5.3.0 that uses natto-py v1.0.0.
:link: https://github.com/himkt/konoha/releases/tag/v5.3.0
