### ISSUE TITLE
Relax requirements on Python forward compatibility packages

### ISSUE THREAD

**Issue by daskol** [himkt/konoha#172]
There is too strong constraint on `importlib-metadata` package which is "official" package for providing feature of the newer version of Python to the older ones. You fixed the package version up to major `4`. It breaks transitive dependencies via `markdown` and `tensorboard` to `torch`  for Python 3.8.

Nothing is actually broken except dependency resolution. By the moment, the latest `importlib-metadata`  package has version `6`.

**Comment by himkt** [comment]
Hi @daskol, thank you for kindly reporting the issue.
I agree that the `importlib-metadata` constraint of `konoha` is too strong and just released v5.4.0 to relax the restriction.
https://github.com/himkt/konoha/releases/tag/v5.4.0
This release changed the dependency from `^4.0.0` to `>=4.0.0,<7.0.0`.
