### ISSUE TITLE
Unpin old overrides v3

### ISSUE THREAD

**Issue by elgalu** [himkt/konoha#178]
https://github.com/himkt/konoha/blob/fa5ff203eac878fc0ed5fef873f98749a23361b9/pyproject.toml#L15

overrides is on version 7 by now

**Comment by himkt** [comment]
Thank you @elgalu for reporting the issue.
I just released konoha v5.5.1 that includes a bunch of dependency updates.

**Comment by himkt** [comment]
@elgalu 
Let me close this issue. Please feel free to reopen if you still found an issue.
Again, thank you for your report.

**Comment by elgalu** [comment]
Hi, I still get this error:

```
konoha 5.5.2  is not installable because it requires overrides >=3.0.0,<4.0.0
```

**Comment by himkt** [comment]
Thank you @elgalu, I just noticed konoha is hosted on conda-forge.
And I found [`meta.yaml`](https://github.com/conda-forge/konoha-feedstock/blob/5ca7d453d63561191534ec76d5ba08a15be348c0/recipe/meta.yaml) was outdated. I'll contact the maintainer. Sorry for inconvenience but please wait additional moments.

**Comment by himkt** [comment]
🔗 https://github.com/conda-forge/konoha-feedstock/pull/14

**Comment by himkt** [comment]
Thank you @elgalu, and sorry to hear that. Currently extras seems not to be supported in conda...

But sphinx related things are not the dependencies of the package itself. It would be acceptable to remove from conda's manifest. I will create another PR to work on that.
