### ISSUE TITLE
Support `Nagisa`.

### ISSUE THREAD

**Issue by himkt** [himkt/konoha#87]

**Comment by upura** [comment]
May I try this? I love using `nagisa` and would like to support it in `Konoha`.

I checked the current implementation and wrote down the tasks.

- [ ] Create `./konoha/word_tokenizers/nagisa_tokenizer.py`
- [ ] Create `./tests/word_tokenizer/test_nagisa_tokenizer.py`
- [ ] Update docs and examples
- [ ] Check package dependencies and installation settings

`nagisa` can output both surface and POS-tags as follows. I believe that `kytea_tokenizer.py` is a good example.
```python
# Get a list of words
print(words.words)
#=> ['Python', 'で', '簡単', 'に', '使える', 'ツール', 'です']

# Get a list of POS-tags
print(words.postags)
#=> ['名詞', '助詞', '形状詞', '助動詞', '動詞', '名詞', '助動詞']
```
https://github.com/taishi-i/nagisa

If there are anything you want me to do, please tell me. Thank you for the wonderful NLP packages.

**Comment by himkt** [comment]
@upura 

Thank you for you interest! I'm happy to review a PR that adds support of Nagisa.
(This issue was closed as I couldn't make time to work.)

Tasks you mentioned basically look good.
I think one more step would be required: register `NagisaTokenizer` to `WordTokenizer`.
([example](https://github.com/himkt/konoha/blob/master/konoha/word_tokenizer.py#L55-L58))

If you have something trouble, please feel free to ask. :pray:

**Comment by upura** [comment]
Thank you, the task lists are updated. I'll submit PR!
